export interface PeriodicElement {
  symbol: string
  name: string
  atomicNumber: number
  atomicMass: number
  electronegativity: number | null
  category: string
  period: number
  group: number
  electronConfiguration: string
  valenceElectrons: number
  color: string
  stateAtRoomTemp: 'solid' | 'liquid' | 'gas'
  isRadioactive: boolean
  commonValences: number[]
  description: string
}

export const PERIODIC_TABLE: PeriodicElement[] = [
  // Period 1
  { symbol: 'H', name: 'Hydrogen', atomicNumber: 1, atomicMass: 1.008, electronegativity: 2.20, category: 'nonmetal', period: 1, group: 1, electronConfiguration: '1s¹', valenceElectrons: 1, color: '#FFFFFF', stateAtRoomTemp: 'gas', isRadioactive: false, commonValences: [1], description: 'The lightest and most abundant element in the universe' },
  { symbol: 'He', name: 'Helium', atomicNumber: 2, atomicMass: 4.003, electronegativity: null, category: 'noble gas', period: 1, group: 18, electronConfiguration: '1s²', valenceElectrons: 2, color: '#D9FFFF', stateAtRoomTemp: 'gas', isRadioactive: false, commonValences: [0], description: 'Second most abundant element in the universe, chemically inert' },
  
  // Period 2
  { symbol: 'Li', name: 'Lithium', atomicNumber: 3, atomicMass: 6.941, electronegativity: 0.98, category: 'alkali metal', period: 2, group: 1, electronConfiguration: '[He] 2s¹', valenceElectrons: 1, color: '#CC80FF', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [1], description: 'Lightest metal, used in batteries and psychiatric medication' },
  { symbol: 'Be', name: 'Beryllium', atomicNumber: 4, atomicMass: 9.012, electronegativity: 1.57, category: 'alkaline earth metal', period: 2, group: 2, electronConfiguration: '[He] 2s²', valenceElectrons: 2, color: '#C2FF00', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [2], description: 'Steel-gray metal, used in aerospace applications' },
  { symbol: 'B', name: 'Boron', atomicNumber: 5, atomicMass: 10.811, electronegativity: 2.04, category: 'metalloid', period: 2, group: 13, electronConfiguration: '[He] 2s² 2p¹', valenceElectrons: 3, color: '#FFB5B5', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [3], description: 'Essential for plant growth, used in glass and ceramics' },
  { symbol: 'C', name: 'Carbon', atomicNumber: 6, atomicMass: 12.011, electronegativity: 2.55, category: 'nonmetal', period: 2, group: 14, electronConfiguration: '[He] 2s² 2p²', valenceElectrons: 4, color: '#909090', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [4, -4], description: 'Basis of all organic life, forms diamonds and graphite' },
  { symbol: 'N', name: 'Nitrogen', atomicNumber: 7, atomicMass: 14.007, electronegativity: 3.04, category: 'nonmetal', period: 2, group: 15, electronConfiguration: '[He] 2s² 2p³', valenceElectrons: 5, color: '#3050F8', stateAtRoomTemp: 'gas', isRadioactive: false, commonValences: [-3, 3, 5], description: 'Makes up 78% of Earths atmosphere, essential for proteins' },
  { symbol: 'O', name: 'Oxygen', atomicNumber: 8, atomicMass: 15.999, electronegativity: 3.44, category: 'nonmetal', period: 2, group: 16, electronConfiguration: '[He] 2s² 2p⁴', valenceElectrons: 6, color: '#FF0D0D', stateAtRoomTemp: 'gas', isRadioactive: false, commonValences: [-2], description: 'Essential for respiration and combustion' },
  { symbol: 'F', name: 'Fluorine', atomicNumber: 9, atomicMass: 18.998, electronegativity: 3.98, category: 'halogen', period: 2, group: 17, electronConfiguration: '[He] 2s² 2p⁵', valenceElectrons: 7, color: '#90E050', stateAtRoomTemp: 'gas', isRadioactive: false, commonValences: [-1], description: 'Most electronegative element, used in toothpaste' },
  { symbol: 'Ne', name: 'Neon', atomicNumber: 10, atomicMass: 20.180, electronegativity: null, category: 'noble gas', period: 2, group: 18, electronConfiguration: '[He] 2s² 2p⁶', valenceElectrons: 8, color: '#B3E3F5', stateAtRoomTemp: 'gas', isRadioactive: false, commonValences: [0], description: 'Inert gas used in neon signs and lighting' },
  
  // Period 3
  { symbol: 'Na', name: 'Sodium', atomicNumber: 11, atomicMass: 22.990, electronegativity: 0.93, category: 'alkali metal', period: 3, group: 1, electronConfiguration: '[Ne] 3s¹', valenceElectrons: 1, color: '#AB5CF2', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [1], description: 'Essential for nerve function, main component of salt' },
  { symbol: 'Mg', name: 'Magnesium', atomicNumber: 12, atomicMass: 24.305, electronegativity: 1.31, category: 'alkaline earth metal', period: 3, group: 2, electronConfiguration: '[Ne] 3s²', valenceElectrons: 2, color: '#8AFF00', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [2], description: 'Light metal used in alloys and fireworks' },
  { symbol: 'Al', name: 'Aluminum', atomicNumber: 13, atomicMass: 26.982, electronegativity: 1.61, category: 'post-transition metal', period: 3, group: 13, electronConfiguration: '[Ne] 3s² 3p¹', valenceElectrons: 3, color: '#BFA6A6', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [3], description: 'Most abundant metal in Earths crust, used in cans and foil' },
  { symbol: 'Si', name: 'Silicon', atomicNumber: 14, atomicMass: 28.086, electronegativity: 1.90, category: 'metalloid', period: 3, group: 14, electronConfiguration: '[Ne] 3s² 3p²', valenceElectrons: 4, color: '#F0C8A0', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [4, -4], description: 'Semiconductor material, basis of computer chips' },
  { symbol: 'P', name: 'Phosphorus', atomicNumber: 15, atomicMass: 30.974, electronegativity: 2.19, category: 'nonmetal', period: 3, group: 15, electronConfiguration: '[Ne] 3s² 3p³', valenceElectrons: 5, color: '#FF8000', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [-3, 3, 5], description: 'Essential for DNA and ATP, used in matches' },
  { symbol: 'S', name: 'Sulfur', atomicNumber: 16, atomicMass: 32.065, electronegativity: 2.58, category: 'nonmetal', period: 3, group: 16, electronConfiguration: '[Ne] 3s² 3p⁴', valenceElectrons: 6, color: '#FFFF30', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [-2, 4, 6], description: 'Yellow solid, used in gunpowder and rubber' },
  { symbol: 'Cl', name: 'Chlorine', atomicNumber: 17, atomicMass: 35.453, electronegativity: 3.16, category: 'halogen', period: 3, group: 17, electronConfiguration: '[Ne] 3s² 3p⁵', valenceElectrons: 7, color: '#1FF01F', stateAtRoomTemp: 'gas', isRadioactive: false, commonValences: [-1, 1, 3, 5, 7], description: 'Toxic gas used for water purification' },
  { symbol: 'Ar', name: 'Argon', atomicNumber: 18, atomicMass: 39.948, electronegativity: null, category: 'noble gas', period: 3, group: 18, electronConfiguration: '[Ne] 3s² 3p⁶', valenceElectrons: 8, color: '#80D1E3', stateAtRoomTemp: 'gas', isRadioactive: false, commonValences: [0], description: 'Inert gas used in welding and light bulbs' },
  
  // Period 4
  { symbol: 'K', name: 'Potassium', atomicNumber: 19, atomicMass: 39.098, electronegativity: 0.82, category: 'alkali metal', period: 4, group: 1, electronConfiguration: '[Ar] 4s¹', valenceElectrons: 1, color: '#8F40D4', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [1], description: 'Essential for muscle and nerve function' },
  { symbol: 'Ca', name: 'Calcium', atomicNumber: 20, atomicMass: 40.078, electronegativity: 1.00, category: 'alkaline earth metal', period: 4, group: 2, electronConfiguration: '[Ar] 4s²', valenceElectrons: 2, color: '#3DFF00', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [2], description: 'Essential for bones and teeth' },
  { symbol: 'Sc', name: 'Scandium', atomicNumber: 21, atomicMass: 44.956, electronegativity: 1.36, category: 'transition metal', period: 4, group: 3, electronConfiguration: '[Ar] 3d¹ 4s²', valenceElectrons: 3, color: '#E6E6E6', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [3], description: 'Rare earth metal used in aerospace alloys' },
  { symbol: 'Ti', name: 'Titanium', atomicNumber: 22, atomicMass: 47.867, electronegativity: 1.54, category: 'transition metal', period: 4, group: 4, electronConfiguration: '[Ar] 3d² 4s²', valenceElectrons: 4, color: '#BFC2C7', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [4], description: 'Strong, lightweight metal used in aircraft and implants' },
  { symbol: 'V', name: 'Vanadium', atomicNumber: 23, atomicMass: 50.942, electronegativity: 1.63, category: 'transition metal', period: 4, group: 5, electronConfiguration: '[Ar] 3d³ 4s²', valenceElectrons: 5, color: '#A6A6AB', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [5, 4, 3, 2], description: 'Used in steel alloys for tools and springs' },
  { symbol: 'Cr', name: 'Chromium', atomicNumber: 24, atomicMass: 51.996, electronegativity: 1.66, category: 'transition metal', period: 4, group: 6, electronConfiguration: '[Ar] 3d⁵ 4s¹', valenceElectrons: 6, color: '#8A99C7', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [6, 3, 2], description: 'Used in stainless steel and chrome plating' },
  { symbol: 'Mn', name: 'Manganese', atomicNumber: 25, atomicMass: 54.938, electronegativity: 1.55, category: 'transition metal', period: 4, group: 7, electronConfiguration: '[Ar] 3d⁵ 4s²', valenceElectrons: 7, color: '#9C7AC7', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [7, 4, 2], description: 'Essential for steel production and battery manufacturing' },
  { symbol: 'Fe', name: 'Iron', atomicNumber: 26, atomicMass: 55.845, electronegativity: 1.83, category: 'transition metal', period: 4, group: 8, electronConfiguration: '[Ar] 3d⁶ 4s²', valenceElectrons: 8, color: '#E06633', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [3, 2], description: 'Most common element on Earth, basis of steel' },
  { symbol: 'Co', name: 'Cobalt', atomicNumber: 27, atomicMass: 58.933, electronegativity: 1.88, category: 'transition metal', period: 4, group: 9, electronConfiguration: '[Ar] 3d⁷ 4s²', valenceElectrons: 9, color: '#F090A0', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [3, 2], description: 'Used in magnets, alloys, and vitamin B12' },
  { symbol: 'Ni', name: 'Nickel', atomicNumber: 28, atomicMass: 58.693, electronegativity: 1.91, category: 'transition metal', period: 4, group: 10, electronConfiguration: '[Ar] 3d⁸ 4s²', valenceElectrons: 10, color: '#50D050', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [2], description: 'Used in stainless steel and coinage' },
  { symbol: 'Cu', name: 'Copper', atomicNumber: 29, atomicMass: 63.546, electronegativity: 1.90, category: 'transition metal', period: 4, group: 11, electronConfiguration: '[Ar] 3d¹⁰ 4s¹', valenceElectrons: 11, color: '#C88033', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [2, 1], description: 'Excellent conductor, used in wiring and coins' },
  { symbol: 'Zn', name: 'Zinc', atomicNumber: 30, atomicMass: 65.38, electronegativity: 1.65, category: 'transition metal', period: 4, group: 12, electronConfiguration: '[Ar] 3d¹⁰ 4s²', valenceElectrons: 12, color: '#7C80B0', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [2], description: 'Used for galvanizing steel and in batteries' },
  { symbol: 'Ga', name: 'Gallium', atomicNumber: 31, atomicMass: 69.723, electronegativity: 1.81, category: 'post-transition metal', period: 4, group: 13, electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p¹', valenceElectrons: 3, color: '#C28F8F', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [3], description: 'Melts in hand, used in semiconductors' },
  { symbol: 'Ge', name: 'Germanium', atomicNumber: 32, atomicMass: 72.64, electronegativity: 2.01, category: 'metalloid', period: 4, group: 14, electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p²', valenceElectrons: 4, color: '#668F8F', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [4], description: 'Semiconductor material, used in fiber optics' },
  { symbol: 'As', name: 'Arsenic', atomicNumber: 33, atomicMass: 74.922, electronegativity: 2.18, category: 'metalloid', period: 4, group: 15, electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p³', valenceElectrons: 5, color: '#BD80E3', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [5, 3, -3], description: 'Toxic metalloid, historically used as poison' },
  { symbol: 'Se', name: 'Selenium', atomicNumber: 34, atomicMass: 78.96, electronegativity: 2.55, category: 'nonmetal', period: 4, group: 16, electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p⁴', valenceElectrons: 6, color: '#FFA100', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [6, 4, -2], description: 'Essential trace element, used in glass production' },
  { symbol: 'Br', name: 'Bromine', atomicNumber: 35, atomicMass: 79.904, electronegativity: 2.96, category: 'halogen', period: 4, group: 17, electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p⁵', valenceElectrons: 7, color: '#A62929', stateAtRoomTemp: 'liquid', isRadioactive: false, commonValences: [-1, 1, 3, 5, 7], description: 'Red-brown liquid, used in flame retardants' },
  { symbol: 'Kr', name: 'Krypton', atomicNumber: 36, atomicMass: 83.798, electronegativity: 3.00, category: 'noble gas', period: 4, group: 18, electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p⁶', valenceElectrons: 8, color: '#5CB8D1', stateAtRoomTemp: 'gas', isRadioactive: false, commonValences: [0], description: 'Inert gas used in high-performance lighting' },

  // Period 5
  { symbol: 'Rb', name: 'Rubidium', atomicNumber: 37, atomicMass: 85.468, electronegativity: 0.82, category: 'alkali metal', period: 5, group: 1, electronConfiguration: '[Kr] 5s¹', valenceElectrons: 1, color: '#702EB0', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [1], description: 'Highly reactive metal, ignites in air' },
  { symbol: 'Sr', name: 'Strontium', atomicNumber: 38, atomicMass: 87.62, electronegativity: 0.95, category: 'alkaline earth metal', period: 5, group: 2, electronConfiguration: '[Kr] 5s²', valenceElectrons: 2, color: '#00FF00', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [2], description: 'Used in fireworks for red color' },
  { symbol: 'Y', name: 'Yttrium', atomicNumber: 39, atomicMass: 88.906, electronegativity: 1.22, category: 'transition metal', period: 5, group: 3, electronConfiguration: '[Kr] 4d¹ 5s²', valenceElectrons: 3, color: '#94FFFF', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [3], description: 'Used in LEDs and phosphors' },
  { symbol: 'Zr', name: 'Zirconium', atomicNumber: 40, atomicMass: 91.224, electronegativity: 1.33, category: 'transition metal', period: 5, group: 4, electronConfiguration: '[Kr] 4d² 5s²', valenceElectrons: 4, color: '#94E0E0', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [4], description: 'Highly corrosion resistant, used in nuclear reactors' },
  { symbol: 'Nb', name: 'Niobium', atomicNumber: 41, atomicMass: 92.906, electronegativity: 1.6, category: 'transition metal', period: 5, group: 5, electronConfiguration: '[Kr] 4d⁴ 5s¹', valenceElectrons: 5, color: '#73C2C9', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [5, 3], description: 'Used in superconducting alloys' },
  { symbol: 'Mo', name: 'Molybdenum', atomicNumber: 42, atomicMass: 95.95, electronegativity: 2.16, category: 'transition metal', period: 5, group: 6, electronConfiguration: '[Kr] 4d⁵ 5s¹', valenceElectrons: 6, color: '#54B5B5', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [6, 4], description: 'High melting point, used in steel alloys' },
  { symbol: 'Tc', name: 'Technetium', atomicNumber: 43, atomicMass: 98, electronegativity: 1.9, category: 'transition metal', period: 5, group: 7, electronConfiguration: '[Kr] 4d⁵ 5s²', valenceElectrons: 7, color: '#3B9E9E', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [7, 4], description: 'First artificially produced element' },
  { symbol: 'Ru', name: 'Ruthenium', atomicNumber: 44, atomicMass: 101.07, electronegativity: 2.2, category: 'transition metal', period: 5, group: 8, electronConfiguration: '[Kr] 4d⁷ 5s¹', valenceElectrons: 8, color: '#248F8F', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [3, 4], description: 'Used in electrical contacts and resistors' },
  { symbol: 'Rh', name: 'Rhodium', atomicNumber: 45, atomicMass: 102.91, electronegativity: 2.28, category: 'transition metal', period: 5, group: 9, electronConfiguration: '[Kr] 4d⁸ 5s¹', valenceElectrons: 9, color: '#0A7D8C', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [3], description: 'Rarest and most valuable precious metal' },
  { symbol: 'Pd', name: 'Palladium', atomicNumber: 46, atomicMass: 106.42, electronegativity: 2.20, category: 'transition metal', period: 5, group: 10, electronConfiguration: '[Kr] 4d¹⁰', valenceElectrons: 10, color: '#006985', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [2, 4], description: 'Used in catalytic converters' },
  { symbol: 'Ag', name: 'Silver', atomicNumber: 47, atomicMass: 107.87, electronegativity: 1.93, category: 'transition metal', period: 5, group: 11, electronConfiguration: '[Kr] 4d¹⁰ 5s¹', valenceElectrons: 11, color: '#C0C0C0', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [1], description: 'Highest electrical conductivity of any metal' },
  { symbol: 'Cd', name: 'Cadmium', atomicNumber: 48, atomicMass: 112.41, electronegativity: 1.69, category: 'transition metal', period: 5, group: 12, electronConfiguration: '[Kr] 4d¹⁰ 5s²', valenceElectrons: 12, color: '#FFD98F', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [2], description: 'Toxic metal used in batteries and pigments' },
  { symbol: 'In', name: 'Indium', atomicNumber: 49, atomicMass: 114.82, electronegativity: 1.78, category: 'post-transition metal', period: 5, group: 13, electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p¹', valenceElectrons: 3, color: '#A67573', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [3], description: 'Used in touch screens and LCDs' },
  { symbol: 'Sn', name: 'Tin', atomicNumber: 50, atomicMass: 118.71, electronegativity: 1.96, category: 'post-transition metal', period: 5, group: 14, electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p²', valenceElectrons: 4, color: '#668080', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [4, 2], description: 'Used to coat other metals to prevent corrosion' },
  { symbol: 'Sb', name: 'Antimony', atomicNumber: 51, atomicMass: 121.76, electronegativity: 2.05, category: 'metalloid', period: 5, group: 15, electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p³', valenceElectrons: 5, color: '#9E63B5', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [3, 5], description: 'Used in flame retardants and lead alloys' },
  { symbol: 'Te', name: 'Tellurium', atomicNumber: 52, atomicMass: 127.60, electronegativity: 2.1, category: 'metalloid', period: 5, group: 16, electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p⁴', valenceElectrons: 6, color: '#D47A00', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [4, -2], description: 'Used in solar panels and alloys' },
  { symbol: 'I', name: 'Iodine', atomicNumber: 53, atomicMass: 126.90, electronegativity: 2.66, category: 'halogen', period: 5, group: 17, electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p⁵', valenceElectrons: 7, color: '#940094', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [-1, 1, 3, 5, 7], description: 'Purple-black solid, essential for thyroid function' },
  { symbol: 'Xe', name: 'Xenon', atomicNumber: 54, atomicMass: 131.29, electronegativity: 2.6, category: 'noble gas', period: 5, group: 18, electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p⁶', valenceElectrons: 8, color: '#429EB0', stateAtRoomTemp: 'gas', isRadioactive: false, commonValences: [0], description: 'Used in flash lamps and ion thrusters' },

  // Period 6
  { symbol: 'Cs', name: 'Cesium', atomicNumber: 55, atomicMass: 132.91, electronegativity: 0.79, category: 'alkali metal', period: 6, group: 1, electronConfiguration: '[Xe] 6s¹', valenceElectrons: 1, color: '#57178F', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [1], description: 'Most reactive metal, used in atomic clocks' },
  { symbol: 'Ba', name: 'Barium', atomicNumber: 56, atomicMass: 137.33, electronegativity: 0.89, category: 'alkaline earth metal', period: 6, group: 2, electronConfiguration: '[Xe] 6s²', valenceElectrons: 2, color: '#00C900', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [2], description: 'Used in medical imaging and drilling fluids' },
  
  // Lanthanides
  { symbol: 'La', name: 'Lanthanum', atomicNumber: 57, atomicMass: 138.91, electronegativity: 1.1, category: 'lanthanide', period: 6, group: 3, electronConfiguration: '[Xe] 5d¹ 6s²', valenceElectrons: 3, color: '#70D4FF', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [3], description: 'Used in hybrid car batteries' },
  { symbol: 'Ce', name: 'Cerium', atomicNumber: 58, atomicMass: 140.12, electronegativity: 1.12, category: 'lanthanide', period: 6, group: 3, electronConfiguration: '[Xe] 4f¹ 5d¹ 6s²', valenceElectrons: 4, color: '#FFFFC7', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [3, 4], description: 'Most abundant rare earth metal' },
  { symbol: 'Pr', name: 'Praseodymium', atomicNumber: 59, atomicMass: 140.91, electronegativity: 1.13, category: 'lanthanide', period: 6, group: 3, electronConfiguration: '[Xe] 4f³ 6s²', valenceElectrons: 3, color: '#D9FFC7', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [3], description: 'Used in strong magnets and green glass' },
  { symbol: 'Nd', name: 'Neodymium', atomicNumber: 60, atomicMass: 144.24, electronegativity: 1.14, category: 'lanthanide', period: 6, group: 3, electronConfiguration: '[Xe] 4f⁴ 6s²', valenceElectrons: 3, color: '#C7FFC7', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [3], description: 'Makes the strongest known permanent magnets' },
  { symbol: 'Pm', name: 'Promethium', atomicNumber: 61, atomicMass: 145, electronegativity: 1.13, category: 'lanthanide', period: 6, group: 3, electronConfiguration: '[Xe] 4f⁵ 6s²', valenceElectrons: 3, color: '#A3FFC7', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [3], description: 'Radioactive rare earth metal' },
  { symbol: 'Sm', name: 'Samarium', atomicNumber: 62, atomicMass: 150.36, electronegativity: 1.17, category: 'lanthanide', period: 6, group: 3, electronConfiguration: '[Xe] 4f⁶ 6s²', valenceElectrons: 3, color: '#8FFFC7', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [3], description: 'Used in magnets and cancer treatment' },
  { symbol: 'Eu', name: 'Europium', atomicNumber: 63, atomicMass: 151.96, electronegativity: 1.2, category: 'lanthanide', period: 6, group: 3, electronConfiguration: '[Xe] 4f⁷ 6s²', valenceElectrons: 3, color: '#61FFC7', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [3, 2], description: 'Used in red phosphors for screens' },
  { symbol: 'Gd', name: 'Gadolinium', atomicNumber: 64, atomicMass: 157.25, electronegativity: 1.2, category: 'lanthanide', period: 6, group: 3, electronConfiguration: '[Xe] 4f⁷ 5d¹ 6s²', valenceElectrons: 3, color: '#45FFC7', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [3], description: 'Used in MRI contrast agents' },
  { symbol: 'Tb', name: 'Terbium', atomicNumber: 65, atomicMass: 158.93, electronegativity: 1.2, category: 'lanthanide', period: 6, group: 3, electronConfiguration: '[Xe] 4f⁹ 6s²', valenceElectrons: 3, color: '#30FFC7', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [3], description: 'Used in green phosphors' },
  { symbol: 'Dy', name: 'Dysprosium', atomicNumber: 66, atomicMass: 162.50, electronegativity: 1.22, category: 'lanthanide', period: 6, group: 3, electronConfiguration: '[Xe] 4f¹⁰ 6s²', valenceElectrons: 3, color: '#1FFFC7', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [3], description: 'Used in nuclear reactor control rods' },
  { symbol: 'Ho', name: 'Holmium', atomicNumber: 67, atomicMass: 164.93, electronegativity: 1.23, category: 'lanthanide', period: 6, group: 3, electronConfiguration: '[Xe] 4f¹¹ 6s²', valenceElectrons: 3, color: '#00FF9C', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [3], description: 'Has highest magnetic strength of any element' },
  { symbol: 'Er', name: 'Erbium', atomicNumber: 68, atomicMass: 167.26, electronegativity: 1.24, category: 'lanthanide', period: 6, group: 3, electronConfiguration: '[Xe] 4f¹² 6s²', valenceElectrons: 3, color: '#00E675', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [3], description: 'Used in fiber optic amplifiers' },
  { symbol: 'Tm', name: 'Thulium', atomicNumber: 69, atomicMass: 168.93, electronegativity: 1.25, category: 'lanthanide', period: 6, group: 3, electronConfiguration: '[Xe] 4f¹³ 6s²', valenceElectrons: 3, color: '#00D452', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [3], description: 'Least abundant stable rare earth' },
  { symbol: 'Yb', name: 'Ytterbium', atomicNumber: 70, atomicMass: 173.04, electronegativity: 1.1, category: 'lanthanide', period: 6, group: 3, electronConfiguration: '[Xe] 4f¹⁴ 6s²', valenceElectrons: 3, color: '#00BF38', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [3, 2], description: 'Used in atomic clocks' },
  { symbol: 'Lu', name: 'Lutetium', atomicNumber: 71, atomicMass: 174.97, electronegativity: 1.27, category: 'lanthanide', period: 6, group: 3, electronConfiguration: '[Xe] 4f¹⁴ 5d¹ 6s²', valenceElectrons: 3, color: '#00AB24', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [3], description: 'Hardest and densest lanthanide' },
  
  // Period 6 Continued
  { symbol: 'Hf', name: 'Hafnium', atomicNumber: 72, atomicMass: 178.49, electronegativity: 1.3, category: 'transition metal', period: 6, group: 4, electronConfiguration: '[Xe] 4f¹⁴ 5d² 6s²', valenceElectrons: 4, color: '#4DC2FF', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [4], description: 'Used in nuclear control rods' },
  { symbol: 'Ta', name: 'Tantalum', atomicNumber: 73, atomicMass: 180.95, electronegativity: 1.5, category: 'transition metal', period: 6, group: 5, electronConfiguration: '[Xe] 4f¹⁴ 5d³ 6s²', valenceElectrons: 5, color: '#4DA6FF', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [5], description: 'Highly corrosion resistant, used in capacitors' },
  { symbol: 'W', name: 'Tungsten', atomicNumber: 74, atomicMass: 183.84, electronegativity: 2.36, category: 'transition metal', period: 6, group: 6, electronConfiguration: '[Xe] 4f¹⁴ 5d⁴ 6s²', valenceElectrons: 6, color: '#2194D6', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [6, 4], description: 'Highest melting point of any metal' },
  { symbol: 'Re', name: 'Rhenium', atomicNumber: 75, atomicMass: 186.21, electronegativity: 1.9, category: 'transition metal', period: 6, group: 7, electronConfiguration: '[Xe] 4f¹⁴ 5d⁵ 6s²', valenceElectrons: 7, color: '#267DAB', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [7, 4], description: 'Used in jet engines' },
  { symbol: 'Os', name: 'Osmium', atomicNumber: 76, atomicMass: 190.23, electronegativity: 2.2, category: 'transition metal', period: 6, group: 8, electronConfiguration: '[Xe] 4f¹⁴ 5d⁶ 6s²', valenceElectrons: 8, color: '#266696', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [4, 8], description: 'Densest natural element' },
  { symbol: 'Ir', name: 'Iridium', atomicNumber: 77, atomicMass: 192.22, electronegativity: 2.2, category: 'transition metal', period: 6, group: 9, electronConfiguration: '[Xe] 4f¹⁴ 5d⁷ 6s²', valenceElectrons: 9, color: '#175487', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [3, 4], description: 'Most corrosion-resistant metal' },
  { symbol: 'Pt', name: 'Platinum', atomicNumber: 78, atomicMass: 195.08, electronegativity: 2.28, category: 'transition metal', period: 6, group: 10, electronConfiguration: '[Xe] 4f¹⁴ 5d⁹ 6s¹', valenceElectrons: 10, color: '#D0D0E0', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [2, 4], description: 'Precious metal used in jewelry and catalysis' },
  { symbol: 'Au', name: 'Gold', atomicNumber: 79, atomicMass: 196.97, electronegativity: 2.54, category: 'transition metal', period: 6, group: 11, electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s¹', valenceElectrons: 11, color: '#FFD123', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [3, 1], description: 'Precious metal, chemically inert and valuable' },
  { symbol: 'Hg', name: 'Mercury', atomicNumber: 80, atomicMass: 200.59, electronegativity: 2.00, category: 'transition metal', period: 6, group: 12, electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s²', valenceElectrons: 12, color: '#B5B5D9', stateAtRoomTemp: 'liquid', isRadioactive: false, commonValences: [2, 1], description: 'Only liquid metal at room temperature, toxic' },
  { symbol: 'Tl', name: 'Thallium', atomicNumber: 81, atomicMass: 204.38, electronegativity: 1.62, category: 'post-transition metal', period: 6, group: 13, electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹', valenceElectrons: 3, color: '#A6544D', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [1, 3], description: 'Highly toxic soft metal' },
  { symbol: 'Pb', name: 'Lead', atomicNumber: 82, atomicMass: 207.2, electronegativity: 2.33, category: 'post-transition metal', period: 6, group: 14, electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²', valenceElectrons: 4, color: '#575961', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [4, 2], description: 'Dense, soft metal, historically used in plumbing and paint' },
  { symbol: 'Bi', name: 'Bismuth', atomicNumber: 83, atomicMass: 208.98, electronegativity: 2.02, category: 'post-transition metal', period: 6, group: 15, electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³', valenceElectrons: 5, color: '#9E4FB5', stateAtRoomTemp: 'solid', isRadioactive: false, commonValences: [3, 5], description: 'Used in cosmetics and medicine' },
  { symbol: 'Po', name: 'Polonium', atomicNumber: 84, atomicMass: 209, electronegativity: 2.0, category: 'post-transition metal', period: 6, group: 16, electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴', valenceElectrons: 6, color: '#AB5C00', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [4, 2], description: 'Highly radioactive, discovered by Marie Curie' },
  { symbol: 'At', name: 'Astatine', atomicNumber: 85, atomicMass: 210, electronegativity: 2.2, category: 'halogen', period: 6, group: 17, electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵', valenceElectrons: 7, color: '#754545', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [-1, 1], description: 'Rarest naturally occurring element' },
  { symbol: 'Rn', name: 'Radon', atomicNumber: 86, atomicMass: 222, electronegativity: 2.2, category: 'noble gas', period: 6, group: 18, electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶', valenceElectrons: 8, color: '#428296', stateAtRoomTemp: 'gas', isRadioactive: true, commonValences: [0], description: 'Radioactive gas, health hazard in homes' },

  // Period 7
  { symbol: 'Fr', name: 'Francium', atomicNumber: 87, atomicMass: 223, electronegativity: 0.7, category: 'alkali metal', period: 7, group: 1, electronConfiguration: '[Rn] 7s¹', valenceElectrons: 1, color: '#420066', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [1], description: 'Highly unstable alkali metal' },
  { symbol: 'Ra', name: 'Radium', atomicNumber: 88, atomicMass: 226, electronegativity: 0.9, category: 'alkaline earth metal', period: 7, group: 2, electronConfiguration: '[Rn] 7s²', valenceElectrons: 2, color: '#007D00', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [2], description: 'Formerly used in glow-in-the-dark paint' },
  
  // Actinides
  { symbol: 'Ac', name: 'Actinium', atomicNumber: 89, atomicMass: 227, electronegativity: 1.1, category: 'actinide', period: 7, group: 3, electronConfiguration: '[Rn] 6d¹ 7s²', valenceElectrons: 3, color: '#70ABFA', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [3], description: 'Glows blue in the dark due to radioactivity' },
  { symbol: 'Th', name: 'Thorium', atomicNumber: 90, atomicMass: 232.04, electronegativity: 1.3, category: 'actinide', period: 7, group: 3, electronConfiguration: '[Rn] 6d² 7s²', valenceElectrons: 4, color: '#00BAFF', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [4], description: 'Potential nuclear fuel' },
  { symbol: 'Pa', name: 'Protactinium', atomicNumber: 91, atomicMass: 231.04, electronegativity: 1.5, category: 'actinide', period: 7, group: 3, electronConfiguration: '[Rn] 5f² 6d¹ 7s²', valenceElectrons: 5, color: '#00A1FF', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [5, 4], description: 'Rare and toxic radioactive metal' },
  { symbol: 'U', name: 'Uranium', atomicNumber: 92, atomicMass: 238.03, electronegativity: 1.38, category: 'actinide', period: 7, group: 3, electronConfiguration: '[Rn] 5f³ 6d¹ 7s²', valenceElectrons: 6, color: '#008FFF', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [6, 4], description: 'Radioactive element used as nuclear fuel' },
  { symbol: 'Np', name: 'Neptunium', atomicNumber: 93, atomicMass: 237, electronegativity: 1.36, category: 'actinide', period: 7, group: 3, electronConfiguration: '[Rn] 5f⁴ 6d¹ 7s²', valenceElectrons: 5, color: '#0080FF', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [5], description: 'Byproduct of nuclear reactors' },
  { symbol: 'Pu', name: 'Plutonium', atomicNumber: 94, atomicMass: 244, electronegativity: 1.28, category: 'actinide', period: 7, group: 3, electronConfiguration: '[Rn] 5f⁶ 7s²', valenceElectrons: 4, color: '#006BFF', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [4], description: 'Used in nuclear weapons' },
  { symbol: 'Am', name: 'Americium', atomicNumber: 95, atomicMass: 243, electronegativity: 1.3, category: 'actinide', period: 7, group: 3, electronConfiguration: '[Rn] 5f⁷ 7s²', valenceElectrons: 3, color: '#545CF2', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [3], description: 'Used in smoke detectors' },
  { symbol: 'Cm', name: 'Curium', atomicNumber: 96, atomicMass: 247, electronegativity: 1.3, category: 'actinide', period: 7, group: 3, electronConfiguration: '[Rn] 5f⁷ 6d¹ 7s²', valenceElectrons: 3, color: '#785CE3', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [3], description: 'Named after Marie and Pierre Curie' },
  { symbol: 'Bk', name: 'Berkelium', atomicNumber: 97, atomicMass: 247, electronegativity: 1.3, category: 'actinide', period: 7, group: 3, electronConfiguration: '[Rn] 5f⁹ 7s²', valenceElectrons: 3, color: '#8A4FE3', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [3], description: 'Synthesized at UC Berkeley' },
  { symbol: 'Cf', name: 'Californium', atomicNumber: 98, atomicMass: 251, electronegativity: 1.3, category: 'actinide', period: 7, group: 3, electronConfiguration: '[Rn] 5f¹⁰ 7s²', valenceElectrons: 3, color: '#A136D4', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [3], description: 'Strong neutron emitter' },
  { symbol: 'Es', name: 'Einsteinium', atomicNumber: 99, atomicMass: 252, electronegativity: 1.3, category: 'actinide', period: 7, group: 3, electronConfiguration: '[Rn] 5f¹¹ 7s²', valenceElectrons: 3, color: '#B31FD4', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [3], description: 'Named after Albert Einstein' },
  { symbol: 'Fm', name: 'Fermium', atomicNumber: 100, atomicMass: 257, electronegativity: 1.3, category: 'actinide', period: 7, group: 3, electronConfiguration: '[Rn] 5f¹² 7s²', valenceElectrons: 3, color: '#B31FBA', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [3], description: 'Named after Enrico Fermi' },
  { symbol: 'Md', name: 'Mendelevium', atomicNumber: 101, atomicMass: 258, electronegativity: 1.3, category: 'actinide', period: 7, group: 3, electronConfiguration: '[Rn] 5f¹³ 7s²', valenceElectrons: 3, color: '#B30DA6', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [3], description: 'Named after Dmitri Mendeleev' },
  { symbol: 'No', name: 'Nobelium', atomicNumber: 102, atomicMass: 259, electronegativity: 1.3, category: 'actinide', period: 7, group: 3, electronConfiguration: '[Rn] 5f¹⁴ 7s²', valenceElectrons: 2, color: '#BD0D87', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [2], description: 'Named after Alfred Nobel' },
  { symbol: 'Lr', name: 'Lawrencium', atomicNumber: 103, atomicMass: 266, electronegativity: 1.3, category: 'actinide', period: 7, group: 3, electronConfiguration: '[Rn] 5f¹⁴ 7s² 7p¹', valenceElectrons: 3, color: '#C70066', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [3], description: 'Named after Ernest Lawrence' },

  // Period 7 Continued
  { symbol: 'Rf', name: 'Rutherfordium', atomicNumber: 104, atomicMass: 267, electronegativity: null, category: 'transition metal', period: 7, group: 4, electronConfiguration: '[Rn] 5f¹⁴ 6d² 7s²', valenceElectrons: 4, color: '#CC0059', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [4], description: 'Named after Ernest Rutherford' },
  { symbol: 'Db', name: 'Dubnium', atomicNumber: 105, atomicMass: 268, electronegativity: null, category: 'transition metal', period: 7, group: 5, electronConfiguration: '[Rn] 5f¹⁴ 6d³ 7s²', valenceElectrons: 5, color: '#D1004F', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [5], description: 'Named after Dubna, Russia' },
  { symbol: 'Sg', name: 'Seaborgium', atomicNumber: 106, atomicMass: 269, electronegativity: null, category: 'transition metal', period: 7, group: 6, electronConfiguration: '[Rn] 5f¹⁴ 6d⁴ 7s²', valenceElectrons: 6, color: '#D90045', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [6], description: 'Named after Glenn T. Seaborg' },
  { symbol: 'Bh', name: 'Bohrium', atomicNumber: 107, atomicMass: 270, electronegativity: null, category: 'transition metal', period: 7, group: 7, electronConfiguration: '[Rn] 5f¹⁴ 6d⁵ 7s²', valenceElectrons: 7, color: '#E00038', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [7], description: 'Named after Niels Bohr' },
  { symbol: 'Hs', name: 'Hassium', atomicNumber: 108, atomicMass: 269, electronegativity: null, category: 'transition metal', period: 7, group: 8, electronConfiguration: '[Rn] 5f¹⁴ 6d⁶ 7s²', valenceElectrons: 8, color: '#E6002E', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [8], description: 'Named after Hesse, Germany' },
  { symbol: 'Mt', name: 'Meitnerium', atomicNumber: 109, atomicMass: 278, electronegativity: null, category: 'transition metal', period: 7, group: 9, electronConfiguration: '[Rn] 5f¹⁴ 6d⁷ 7s²', valenceElectrons: 9, color: '#EB0026', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [], description: 'Named after Lise Meitner' },
  { symbol: 'Ds', name: 'Darmstadtium', atomicNumber: 110, atomicMass: 281, electronegativity: null, category: 'transition metal', period: 7, group: 10, electronConfiguration: '[Rn] 5f¹⁴ 6d⁹ 7s¹', valenceElectrons: 10, color: '#EB0026', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [], description: 'Named after Darmstadt, Germany' },
  { symbol: 'Rg', name: 'Roentgenium', atomicNumber: 111, atomicMass: 282, electronegativity: null, category: 'transition metal', period: 7, group: 11, electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s¹', valenceElectrons: 11, color: '#EB0026', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [], description: 'Named after Wilhelm Roentgen' },
  { symbol: 'Cn', name: 'Copernicium', atomicNumber: 112, atomicMass: 285, electronegativity: null, category: 'transition metal', period: 7, group: 12, electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s²', valenceElectrons: 12, color: '#EB0026', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [], description: 'Named after Nicolaus Copernicus' },
  { symbol: 'Nh', name: 'Nihonium', atomicNumber: 113, atomicMass: 286, electronegativity: null, category: 'post-transition metal', period: 7, group: 13, electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹', valenceElectrons: 3, color: '#EB0026', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [], description: 'Named after Japan' },
  { symbol: 'Fl', name: 'Flerovium', atomicNumber: 114, atomicMass: 289, electronegativity: null, category: 'post-transition metal', period: 7, group: 14, electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²', valenceElectrons: 4, color: '#EB0026', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [], description: 'Named after Flerov Laboratory' },
  { symbol: 'Mc', name: 'Moscovium', atomicNumber: 115, atomicMass: 290, electronegativity: null, category: 'post-transition metal', period: 7, group: 15, electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³', valenceElectrons: 5, color: '#EB0026', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [], description: 'Named after Moscow' },
  { symbol: 'Lv', name: 'Livermorium', atomicNumber: 116, atomicMass: 293, electronegativity: null, category: 'post-transition metal', period: 7, group: 16, electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴', valenceElectrons: 6, color: '#EB0026', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [], description: 'Named after Lawrence Livermore National Laboratory' },
  { symbol: 'Ts', name: 'Tennessine', atomicNumber: 117, atomicMass: 294, electronegativity: null, category: 'halogen', period: 7, group: 17, electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵', valenceElectrons: 7, color: '#EB0026', stateAtRoomTemp: 'solid', isRadioactive: true, commonValences: [], description: 'Named after Tennessee' },
  { symbol: 'Og', name: 'Oganesson', atomicNumber: 118, atomicMass: 294, electronegativity: null, category: 'noble gas', period: 7, group: 18, electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶', valenceElectrons: 8, color: '#FFFFFF', stateAtRoomTemp: 'gas', isRadioactive: true, commonValences: [0], description: 'Synthetic superheavy element, highly unstable' }
]

// Element categories for filtering
export const ELEMENT_CATEGORIES = {
  'alkali metal': { color: '#CC80FF', label: 'Alkali Metals' },
  'alkaline earth metal': { color: '#8AFF00', label: 'Alkaline Earth Metals' },
  'transition metal': { color: '#E06633', label: 'Transition Metals' },
  'post-transition metal': { color: '#BFA6A6', label: 'Post-Transition Metals' },
  'metalloid': { color: '#F0C8A0', label: 'Metalloids' },
  'nonmetal': { color: '#909090', label: 'Nonmetals' },
  'halogen': { color: '#1FF01F', label: 'Halogens' },
  'noble gas': { color: '#80D1E3', label: 'Noble Gases' },
  'lanthanide': { color: '#FFBFFF', label: 'Lanthanides' },
  'actinide': { color: '#FF99CC', label: 'Actinides' }
}

// Element groups for organization
export const ELEMENT_GROUPS = {
  1: { name: 'Alkali Metals', color: '#CC80FF' },
  2: { name: 'Alkaline Earth Metals', color: '#8AFF00' },
  3: { name: 'Scandium Group', color: '#E6E6E6' },
  4: { name: 'Titanium Group', color: '#BFC2C7' },
  5: { name: 'Vanadium Group', color: '#A6A6AB' },
  6: { name: 'Chromium Group', color: '#8A99C7' },
  7: { name: 'Manganese Group', color: '#9C7AC7' },
  8: { name: 'Iron Group', color: '#E06633' },
  9: { name: 'Cobalt Group', color: '#F090A0' },
  10: { name: 'Nickel Group', color: '#50D050' },
  11: { name: 'Copper Group', color: '#C88033' },
  12: { name: 'Zinc Group', color: '#7C80B0' },
  13: { name: 'Boron Group', color: '#C28F8F' },
  14: { name: 'Carbon Group', color: '#668F8F' },
  15: { name: 'Nitrogen Group', color: '#BD80E3' },
  16: { name: 'Oxygen Group', color: '#FFA100' },
  17: { name: 'Halogens', color: '#1FF01F' },
  18: { name: 'Noble Gases', color: '#80D1E3' }
}

// Common organic chemistry elements
export const ORGANIC_CHEMISTRY_ELEMENTS = ['H', 'C', 'N', 'O', 'F', 'P', 'S', 'Cl', 'Br', 'I']

// State at room temperature
export const STATE_AT_ROOM_TEMP = {
  solid: { color: '#8B4513', label: 'Solid' },
  liquid: { color: '#4169E1', label: 'Liquid' },
  gas: { color: '#87CEEB', label: 'Gas' }
}

// Radioactivity status
export const RADIOACTIVITY_STATUS = {
  stable: { color: '#32CD32', label: 'Stable' },
  radioactive: { color: '#FF4500', label: 'Radioactive' }
}
